# Generated by Django 5.2.8 on 2025-11-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delatable', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('enroll_date', models.DateField()),
                ('Participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.participants')),
                ('Workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.workshop')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['enroll_date'],
            },
        ),
    ]
