# Generated by Django 5.2.8 on 2025-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delatable', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('field', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delatable', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['name'],
            },
        ),
    ]
