# Generated by Django 5.2.8 on 2025-11-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_product_book_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
