# Generated by Django 5.2.8 on 2025-11-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_laptop_product_ptr_delete_book_delete_laptop_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructor',
            table='Instructor',
        ),
    ]
